{
  "contest": 386,
  "handle": "iam_emptyset",
  "risk": "2",
  "title": "Logic error in _transferOutAndCallV5 internal function",
  "issueId": 82,
  "issueUrl": "https://github.com/code-423n4/2024-06-thorchain-findings/issues/82",
  "originalIssueId": 49,
  "originalIssueUrl": "https://github.com/code-423n4/2024-06-thorchain-validation/issues/49"
}